#!/bin/bash -e
#
# S2I assemble script for the 'aspnet' image.
# The 'assemble' script builds your application source so that it is ready to run.
#
# For more information refer to the documentation:
#	https://github.com/openshift/source-to-image/blob/master/docs/builder_image.md
#

set -e

DOTNET_CONFIGURATION="${DOTNET_CONFIGURATION:-Release}"
DOTNET_STARTUP_PROJECT="${DOTNET_STARTUP_PROJECT:-.}"

if [[ "$1" == "-h" ]]; then
	# If the 'aspnet' assemble script is executed with '-h' flag,
	# print the usage.
	exec /usr/libexec/s2i/usage
fi

echo "---> current working directory"
pwd
echo "---> HOME"
echo ${HOME}

echo "---> Copying application source ..."
ls -a ${HOME}
ls -a /tmp/src
cp -Rf /tmp/src/. ./

# output assembly name
if [ -n "$DOTNET_ASSEMBLY_NAME" ]; then
  APP_DLL_NAME="${DOTNET_ASSEMBLY_NAME}.dll"
else
  APP_DLL_NAME="$(basename "$(realpath "${DOTNET_STARTUP_PROJECT}")").dll"
fi

echo "---> Installing dependencies ..."
dotnet restore $RESTORE_OPTIONS

# build application
echo "---> Building application ..."
dotnet build -f "$DOTNET_FRAMEWORK" -c "$DOTNET_CONFIGURATION" "$DOTNET_STARTUP_PROJECT"

# Fix source directory permissions
fix-permissions ./
# set permissions for any installed artifacts
fix-permissions /opt/app-root
